### ISSUE TITLE
Error in params.pp when puppet_confdir fact is empty.

### ISSUE THREAD

**Issue by claflico** [joshbeard/puppet-bamboo#11]
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Left match operand must result in a String value. Got an Undef Value. at /etc/puppetlabs/code/environments/production/modules/bamboo/manifests/params.pp:26:6 on node dc1-ops-bamboo01.dc1.ourdomain.corp

CentOS 7
puppet-agent-1.4.2-1.el7.x86_64

facter -p puppet_confdir is empty.

**Comment by claflico** [comment]
Also, facter dir is /opt/puppetlabs/facter/facts.d

**Comment by joshbeard** [comment]
Sorry for the delay.  I'll have a fix for this published very shortly.

**Comment by joshbeard** [comment]
Should be good to go there.  Thanks for the feedback!
