### ISSUE TITLE
Service restart is triggered on every run when $server_xml is specified

### ISSUE THREAD

**Issue by durist** [joshbeard/puppet-bamboo#15]
In configure.pp. if $server_xml is set, the module creates the server.xml file like this:
```
  if( $server_xml ){
    file { "${appdir}/conf/server.xml":
      content => $server_xml,
    }
  }
```
Since it doesn't specify owner and group, it will inherit whatever the defaults are for that. If these aren't the bamboo user and group, a restart is triggered on every run by this code in install.pp:

```
  exec { "chown_${appdir}":
    command => "chown -R ${user}:${group} ${appdir}",
    unless  => "find ${appdir} ! -type l \\( ! -user ${user} \\) -o \\( ! -group ${group} \\) | wc -l | awk '{print \$1}' | grep -qE '^0'",
    path    => '/bin:/usr/bin',
  }
```

This can be fixed by making the owner and group explicit for server.xml in configure.pp, like this:

```
  if( $server_xml ){
    file { "${appdir}/conf/server.xml":
      content => $server_xml,
      owner => $user,
      group => $group
    }
  }
```

**Comment by joshbeard** [comment]
@durist Is this still an issue? I'm not sure what the context is here - there is no `server_xml` parameter in the module and it's not managing `server.xml` as a file resource. There's an `augeas` resource that manages a selection of settings, though.

**Comment by joshbeard** [comment]
Closing this for now. If you have more info, feel free to comment again.

As far as I can tell, this comment doesn't reflect the current codebase - the `server.xml` file isn't managed as a file resource. The module currently only uses an `augeas` resource to manage attributes on the connector in `server.xml`
