### ISSUE TITLE
Still under development?

### ISSUE THREAD

**Issue by vrmerlin** [joshbeard/puppet-bamboo#16]
This has been quiet for a year -- is it still under development?

**Comment by vrmerlin** [comment]
I haven't seen any answer, so it must be this is abandoned. That's a shame because it's close to working. I have a couple fixes I was able to do that got it working again.   Isn't there anyone who can work with pull requests to accept fixes?

**Comment by joshbeard** [comment]
I do maintain this and actively use it myself, but it hasn't had any active development.
