### ISSUE TITLE
tomcat_port and proxy not getting set for Bamboo 6.8

### ISSUE THREAD

**Issue by RikyH** [joshbeard/puppet-bamboo#22]
The server.xml is no longer getting modified to set the port or proxy options. This was working for Bamboo 6.4.1, but doesn't for 6.8.1 (sorry, not tried any version in between).

Atlassian have slightly changed the stock server.xml file, and I'm assuming that the augeas in `bamboo::configure` is no longer applying, but I can't figure out why not.

**Comment by joshbeard** [comment]
Thanks for reporting.

I've published 3.5.1 to the Forge with a fix: https://forge.puppet.com/joshbeard/bamboo/3.5.1/readme

Fix: https://github.com/joshbeard/puppet-bamboo/pull/23
