### ISSUE TITLE
/opt/staging/bamboo/atlassian-bamboo-5.9.7.tar.gz: Cannot open: Permission denied

### ISSUE THREAD

**Issue by krinkere** [joshbeard/puppet-bamboo#5]
Getting this error when trying to apply 

class { 'bamboo':
  installdir => '/opt/atlassian/bamboo',
  homedir => '/var/atlassian/application-data/bamboo',
}

as a root user.

I see the file in the mentioned directory as
-rw-------.  1 root root 204873211 Jun 24 11:55 atlassian-bamboo-5.9.7.tar.gz

anything that I am doing wrong?

**Comment by joshbeard** [comment]
@krinkere sorry for the delay.  Did you get this worked out?  Can you apply that with `--debug` and paste the relevant bit around this error?

**Comment by krinkere** [comment]
@joshbeard thanks for getting back to me! I "solved" it by manually creating installdir and homedir and setting the right permissions. A hack, but works :)
